apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
  namespace: ${namespace}
spec:
  type: LoadBalancer 
  selector:
    app: hello-server
  ports:
    - port: 80
      targetPort: 8080