apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-service
  namespace: ${namespace}
spec:
  type: NodePort
  selector:
    app: ${app_name}
  ports:
    - port: 80
      targetPort: 8080
      nodePort: ${service_node_port}
